//! Gate test for Paso 6.f.6: gt-mcp drives the merge domain end-to-end through the
//! `Command { validate, execute }` path.
//!
//! `McpService::run_merge` is the shared dispatch backing every merge `#[tool]` method
//! generated by `#[tool_router]`. Driving it directly covers the same scope + audit + actor
//! path the wire transport hits, without standing up stdio.
//!
//! Covers:
//! - A `read_only` scope rejects `merge.submit.execute` and records `Unauthorized`.
//! - A `validate` of `start` against a missing slot fails cleanly, audited `Invoked { Failed }`.
//! - A full-scope submit/start/complete drives the slot `Ready → Merging → Merged` and emits
//!   exactly that `MergeEvent` sequence on the actor's relay (emit-on-apply preserved).
//! - An illegal transition (`complete` while the slot is still `Ready`) is rejected by the
//!   state machine and audited `Failed`, with no event emitted for it.

use std::sync::Arc;

use serde_json::json;

use gt_events::Envelope;
use gt_merge::actor;
use gt_merge::{CompleteMerge, MergeCommand, MergeEvent, StartMerge, SubmitMerge};
use gt_mcp::{
    audit::{AuditEvent, AuditSink, InMemoryAudit, Outcome},
    auth::Scope,
    McpService,
};

#[tokio::test(flavor = "multi_thread", worker_threads = 2)]
async fn mcp_drives_merge_slot_through_lifecycle_and_emits_events() {
    // The actor's relay: every applied transition is emitted here. We drain it at the end to
    // assert the exact event sequence the MCP calls produced.
    let (merge_tx, mut merge_rx) = tokio::sync::mpsc::channel::<Envelope<MergeEvent>>(16);
    let merge = actor::spawn(merge_tx);

    let watcher_audit = Arc::new(InMemoryAudit::new());
    let watcher = McpService::new(
        actor_agent(),
        merge.clone(),
        actor_sched(),
        actor_patrol(),
        actor_orch(),
        Scope::read_only("watcher"),
        Arc::clone(&watcher_audit) as Arc<dyn AuditSink>,
    );

    let admin_audit = Arc::new(InMemoryAudit::new());
    let admin = McpService::new(
        actor_agent(),
        merge.clone(),
        actor_sched(),
        actor_patrol(),
        actor_orch(),
        Scope::admin("admin"),
        Arc::clone(&admin_audit) as Arc<dyn AuditSink>,
    );

    // watcher tries to submit a merge → blocked by scope; audited Unauthorized.
    let submit = SubmitMerge {
        bead: "b1".into(),
        branch: "feat/x".into(),
        channel_msg_id: "01".into(),
    };
    let denied = watcher
        .run_merge(
            "merge.submit.execute",
            json!({"bead": "b1", "branch": "feat/x", "channel_msg_id": "01"}),
            MergeCommand::Submit(submit.clone()),
            false,
        )
        .await;
    let denied_msg = denied
        .expect_err("execute on read_only must fail")
        .message
        .to_string();
    assert!(denied_msg.contains("validate_only"), "denied msg: {denied_msg}");

    // watcher validates a start on a missing slot → fails cleanly, Invoked { Failed }.
    let validate_missing = watcher
        .run_merge(
            "merge.start.validate",
            json!({"bead": "ghost"}),
            MergeCommand::Start(StartMerge { bead: "ghost".into() }),
            true,
        )
        .await;
    assert!(validate_missing.is_err(), "validate of missing slot must fail");

    // admin submits b1 (Ready), starts (Merging), completes (Merged). All succeed.
    admin
        .run_merge(
            "merge.submit.execute",
            json!({"bead": "b1", "branch": "feat/x", "channel_msg_id": "01"}),
            MergeCommand::Submit(submit),
            false,
        )
        .await
        .expect("admin submit.execute should succeed");

    admin
        .run_merge(
            "merge.start.execute",
            json!({"bead": "b1"}),
            MergeCommand::Start(StartMerge { bead: "b1".into() }),
            false,
        )
        .await
        .expect("admin start.execute Ready -> Merging should succeed");

    admin
        .run_merge(
            "merge.complete.execute",
            json!({"bead": "b1", "sha": "abc"}),
            MergeCommand::Complete(CompleteMerge { bead: "b1".into(), sha: "abc".into() }),
            false,
        )
        .await
        .expect("admin complete.execute Merging -> Merged should succeed");

    // Illegal: complete a slot that is already Merged (terminal) → rejected by state machine.
    let illegal = admin
        .run_merge(
            "merge.complete.execute",
            json!({"bead": "b1", "sha": "def"}),
            MergeCommand::Complete(CompleteMerge { bead: "b1".into(), sha: "def".into() }),
            false,
        )
        .await;
    assert!(illegal.is_err(), "completing a terminal slot must fail");

    // --- the relay carries exactly Ready, Started, Merged (emit-on-apply) -----------------
    // Drop every MergeHandle (the two services each hold a clone) so the actor task ends and
    // its relay sender closes; only then does the drain loop terminate.
    drop(watcher);
    drop(admin);
    drop(merge);
    let mut events = Vec::new();
    while let Some(env) = merge_rx.recv().await {
        events.push(env.payload);
    }
    assert_eq!(
        events,
        vec![
            MergeEvent::Ready {
                bead: "b1".into(),
                branch: "feat/x".into(),
                channel_msg_id: "01".into(),
            },
            MergeEvent::Started { bead: "b1".into() },
            MergeEvent::Merged { bead: "b1".into(), sha: "abc".into() },
        ],
        "only the three legal transitions are emitted; the illegal complete emits nothing",
    );

    // --- audit: watcher saw Unauthorized + failed validate; admin saw 3 Ok + 1 Failed ----
    let watcher_events = watcher_audit.snapshot();
    assert!(
        watcher_events.iter().any(|e| matches!(
            e,
            AuditEvent::Unauthorized { tool, .. } if tool == "merge.submit.execute"
        )),
        "watcher audit missing Unauthorized for submit.execute: {watcher_events:?}",
    );
    assert!(
        watcher_events.iter().any(|e| matches!(
            e,
            AuditEvent::Invoked { tool, outcome: Outcome::Failed { .. }, .. } if tool == "merge.start.validate"
        )),
        "watcher audit missing failed validate: {watcher_events:?}",
    );

    let admin_events = admin_audit.snapshot();
    let ok_count = admin_events
        .iter()
        .filter(|e| matches!(e, AuditEvent::Invoked { outcome: Outcome::Ok, .. }))
        .count();
    assert_eq!(ok_count, 3, "admin: submit+start+complete all Ok: {admin_events:?}");
    assert!(
        admin_events.iter().any(|e| matches!(
            e,
            AuditEvent::Invoked { tool, outcome: Outcome::Failed { .. }, .. } if tool == "merge.complete.execute"
        )),
        "admin audit missing failed illegal complete.execute: {admin_events:?}",
    );
}

/// A throwaway agent actor so the service has its full surface; this gate exercises only merge.
fn actor_agent() -> gt_agent::actor::AgentHandle {
    gt_agent::actor::spawn(16)
}

/// A throwaway scheduling actor so the service has its full surface; relay receiver dropped.
fn actor_sched() -> gt_scheduling::actor::SchedHandle {
    let (tx, _rx) = tokio::sync::mpsc::channel(16);
    gt_scheduling::actor::spawn(Arc::new(gt_beads::InMemoryBeads::default()), tx, 4)
}

/// A throwaway patrol actor so the service has its full surface; relay receiver dropped.
fn actor_patrol() -> gt_patrol::actor::PatrolHandle {
    let (tx, _rx) = tokio::sync::mpsc::channel(16);
    gt_patrol::actor::spawn(tx)
}

/// A throwaway orchestration actor so the service has its full surface; relay receiver dropped.
fn actor_orch() -> gt_orchestration::actor::OrchHandle {
    let (tx, _rx) = tokio::sync::mpsc::channel(16);
    gt_orchestration::actor::spawn(tx)
}
