[package]
name = "gt-store-dolt"
edition.workspace = true
version.workspace = true
rust-version.workspace = true

[dependencies]
gt-events = { path = "../gt-events" }
gt-beads = { path = "../gt-beads" }
gt-agent = { path = "../../domain/gt-agent" }
mysql_async = { workspace = true }

[dev-dependencies]
tokio = { workspace = true }
